Models/ITodoRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace toDoList.Models
{
    public interface ITodoRepository
    {
        Task<IEnumerable<Todo>> GetAll();
        Task Add(Todo todo);
        Task Remove(Guid id);
        Task<Todo> Find(Guid id);
        Task Update(Todo todo);
    }
}

Models/Todo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace toDoList.Models
{
    public class Todo
    {
        public Todo()
        {
            Id = Guid.NewGuid();
        }
        public Guid Id { get; set; }

        [Required]
        public string Description { get; set; }
    }
}

Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using toDoList.Models;

namespace toDoList.Pages
{
    public class EditModel : PageModel
    {
        private readonly ITodoRepository _todoRepository;

        public EditModel(ITodoRepository todoRepository)
        {
            _todoRepository = todoRepository;
        }

        public Todo EditTodo { get; private set; }

        public async Task OnGetAsync(Guid id)
        {
            await GetEditTodo(id);
        }

        public async Task<IActionResult> OnPostAsync(Todo todo)
        {
            if (ModelState.IsValid)
            {
                await _todoRepository.Update(todo);
                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }

        private async Task GetEditTodo(Guid id)
        {
            EditTodo = await _todoRepository.Find(id);
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace toDoList.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using toDoList.Models;
using toDoList.Models;

namespace toDoList.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ITodoRepository _todoRepository;
        public IndexModel(ITodoRepository todoRepository)
        {
            _todoRepository = todoRepository;
        }
        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public IEnumerable<Todo> Todos { get; private set; }

        public async Task OnGetAsync()
        {
            await GetTodos();
        }

        public async Task<IActionResult> OnPostAsync(Todo todo)
        {
            await OnGetAsync();
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _todoRepository.Add(todo);
            Message = $"Added: {todo.Description}";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveAsync(Guid id)
        {
            if (ModelState.IsValid)
            {
                await _todoRepository.Remove(id);
                return RedirectToPage();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostEditAsync(Guid id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if ((await _todoRepository.Find(id) != null))
                return RedirectToPage("Edit", new { id = id });

            return Page();
        }
        private async Task GetTodos()
        {
            Todos = await _todoRepository.GetAll();
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace toDoList.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Edit.cshtml
@page
@model EditModel
@{
    <h1>Todo List</h1>
    <h4>Edit a todo : @Model.EditTodo.Description</h4>
    <form asp-page="Edit" method="post" class="form-inline">
            <input type="hidden" name="Id" value="@Model.EditTodo.Id" />
            <input type="text" id="Description" name="Description" class="form-control" placeholder="Description"/>
            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Update</button>
    </form>
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home Page";
}
<h1>Todo List</h1>
<h4>Add a todo</h4>
<form asp-page="Index" method="post" class="form-inline">
    <input type="text" id="Description" name="Description" class="form-control" placeholder="Description" />
    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add</button>
</form>
<div asp-validation-summary="All"></div>
<h4>Current Todo's</h4>

@if (!Model.Todos.Any())
{
    <p class="empty">The list is empty</p>
}
else
{
    <ul class="list-unstyled">
        @foreach (var todo in Model.Todos)
        {
            <li>
                <form method="post" asp-page="Index" asp-page-handler="Remove" style="display: inline">
                    <input type="hidden" name="Id" value="@todo.Id" />
                    <button type="submit" class="btn btn-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                        </svg>
                    </button>
                </form>
                <form method="post" asp-page="Index" asp-page-handler="Edit" style="display: inline">
                    <input type="hidden" name="Id" value="@todo.Id" />
                    <button type="submit" class="btn btn-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
</svg></button>
                </form>
                @todo.Description
            </li>
        }
    </ul>
}
<style>
    .validation-summary-errors ul {
        list-style-type: none;
        color: red;
        padding: 0;
        margin: 0;
    }

    .empty {
        color: lightgray;
    }
</style>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - toDoList</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">toDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - toDoList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>